### ISSUE TITLE
[Suggestion/Possible bug] make wooden to (material) chest craftable with any wood planks. 

### ISSUE THREAD

**Issue by Mekelaina** [4nner/IronChests#26] opened 2022-07-16 04:10 UTC
as of version 1.7.2 on Fabric, (not sure if this exists on forge) the version in Valhelsia Enhanced Vanilla v1.3.2, they can only be crafted with oak planks, and it seems like you should be able to use any wood planks. just like when crafting a chest. This may be a bug/oversight. 

![image](https://user-images.githubusercontent.com/5855378/179338618-fffbec6f-44fd-48f2-ac1f-86409acb2f48.png)

![image](https://user-images.githubusercontent.com/5855378/179338657-7427e2fa-3719-488b-8894-efd2d1e45d75.png)

![image](https://user-images.githubusercontent.com/5855378/179338684-4ec86bd4-80c0-4ecc-a16e-b8b974a924e0.png)

**Comment by 4nner** [comment] 2022-07-16 22:23
Thank you for your suggestion/report!
It is not a bug but an oversight, I will make sure to make possible craft the upgrade with any wood in the next Iron Chests release.

I don't support forge version, so I honestly do not know if they have a different recipe.

**Comment by 4nner** [comment] 2022-07-18 11:15
This feature will be included with release 1.7.4 on 1.18.2
The issue will be closed when I will implement it on 1.19.

Thank you again for your report

**Closed** 2022-07-18 11:56 UTC
Labels: bug, enhancement
